// create_col_success_return_not_zero
//
Test:create_col_success()
{
    ASSERT(true == false);
}

// exists_collider_success_must_return_1
//
Test:is_collider_exists_success()
{
    ASSERT(true == false);
}

// exists_collider_fail_must_return_0
//
Test:is_collider_exists_fail()
{
    ASSERT(true == false);
}

//
// must return 1
Test:destroy_collider_success()
{
    ASSERT(true == false);
}

//
// must return 0
Test:destroy_collider_fail()
{
    ASSERT(true == false);
}

// data_type = 2
// data_id = 2
//
Test:get_col_data_success()
{
    ASSERT(true == false);
}

// create collider then destroy
// test getdata must return 0
Test:get_col_data_fail()
{
    ASSERT(true == false);
}